[project]
name = "dbt-tpch"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "dbt-duckdb>=1.10.0",
    "dbt-postgres>=1.10.0",
    "psycopg2-binary>=2.9.0",
    "recce>=1.35.0",
]
